language: ruby
before_script:
  - mysql -e 'create database rla_test;'
  - psql -c 'create database rla_test;' -U postgres
script: bundle exec rake
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
gemfile:
  - Gemfile.activerecord2
  - Gemfile.activerecord3
  - Gemfile.activerecord4
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  exclude:
    - gemfile: Gemfile.activerecord2
      rvm: 1.8.7
    - gemfile: Gemfile.activerecord3
      rvm: 1.8.7 
notifications:
  email:
    - info@railsdoctors.com
